name       : python-qt4
version    : 4.11.4
release    : 5
source     :
    - http://netcologne.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz : fc1fe77495432ba3b0d74ff5cb164d375a97f5dddb728256330f615a7cdcf407
license    : GPL-3.0
component  : programming.python
summary    : python-qt4 are the python2 bindings for Qt4.
description: |
    python-qt4 are the python2 bindings for Qt4.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gl)
    - pkgconfig(python-2.7)
    - pkgconfig(QtGui)
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    python2 configure-ng.py --confirm-license --no-sip-files --qsci-api -q /usr/bin/qmake-qt4
build      : |
    ln -s /usr/bin/moc-qt4 /usr/bin/moc
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -d $installdir/usr/share/sip/PyQt4
    cp -r sip/* $installdir/usr/share/sip/PyQt4
    mv $installdir/usr/bin/{,python2-}pyuic4
