name       : python-qt4
version    : '4.12'
release    : 6
source     :
    - https://pilotfiber.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.12/PyQt4_gpl_x11-4.12.tar.gz : 3c1d4b55314adb3e1132de8fc2a92eed216d37e58aceed41294dbca210ca88db
license    : GPL-3.0
component  : programming.python
summary    : python-qt4 are the python2 bindings for Qt4.
description: |
    python-qt4 are the python2 bindings for Qt4.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gl)
    - pkgconfig(python-2.7)
    - pkgconfig(QtGui)
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    python2 configure-ng.py --confirm-license --no-sip-files --qsci-api -q /usr/bin/qmake-qt4
build      : |
    sed -i "s|/usr/bin/moc|/usr/bin/moc-qt4|g" ./*/Makefile
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -d $installdir/usr/share/sip/PyQt4
    cp -r sip/* $installdir/usr/share/sip/PyQt4
    mv $installdir/usr/bin/{,python2-}pyuic4
