name       : python-qt4
version    : 4.12.1
release    : 7
source     :
    - https://netcologne.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.12.1/PyQt4_gpl_x11-4.12.1.tar.gz : 45d724461ae58b019b9be95076ca07e212eb73084aec9125bb254825c3a05383
license    : GPL-3.0
component  : programming.python
summary    : python-qt4 are the python2 bindings for Qt4.
description: |
    python-qt4 are the python2 bindings for Qt4.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(QtGui)
    - python-sip-devel
rundeps    :
    - python-sip
setup      : |
    python2 configure-ng.py --confirm-license \
        --no-sip-files \
        --qsci-api \
        -q /usr/bin/qmake-qt4 \
        CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LFLAGS="$LDFLAGS"
build      : |
    sed -i "s|/usr/bin/moc|/usr/bin/moc-qt4|g" ./*/Makefile
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -d $installdir/usr/share/sip/PyQt4
    cp -r sip/* $installdir/usr/share/sip/PyQt4
    mv $installdir/usr/bin/{,python2-}pyuic4
